### ISSUE TITLE
Error Compiling Code

### ISSUE THREAD

**Issue by UAS-User** [panchazo/open-weather-station#3]
I have all the libraries installed, updated, and in the correct folders, and have not changed the downloaded code at all, yet when I go to compile, I keep getting:

"   no matching function for call to 'SimpleTimer::setInterval(int, void (&)())'   "

There seems to be an issue with the SimpleTimer/timermanager portion of the code that I can't figure out.

**Comment by panchazo** [comment]
Hi, the code is fine, you are just having some library issue, you will need to double check your Arduino libraries and also check that you are using a proper SimpleTimer library. Google is a better source of help on this regards. Best!
