### ISSUE TITLE
APK Android ya no está disponible en Google Play

### ISSUE THREAD

**Issue by gabrielvgaona** [panchazo/open-weather-station#6]
Es muy interesante este proyecto. Me gustaría crear una estación con mis estudiantes de meteorología. Pero al día de hoy, no se encuentra la aplicación en Google Play ¿Existe una versión de la APK disponible en algún otro sitio?

Muchas gracias por compartir todo esto.

**Comment by panchazo** [comment]
Hola Gabriel, Google Play la bajó del store porque hace mucho no recibe
actualizaciones. Pero bajé el último paquete de instalación y ahora está
disponible en el repositorio en el branch master acá esta el link, desde
ahí podes bajar el apk e instalarlo manualmente en el celular:

https://github.com/panchazo/open-weather-station/tree/master/app


Espero les sea de utilidad,

Saludos!!
Fran

**Comment by gabrielvgaona** [comment]
Muchas gracias.
